### ISSUE TITLE
Brightness keys do not work

### ISSUE THREAD

**Issue by Luka020** [Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh#1]
Thank you for your hard work! i have the same Laptop as you do only i have the 720p screen instead of the 1080p.

The thing is my birghtness keys do not work F11 and F12.

They only work if i press FN+P or FN+C

Hope is fixable, Thank you

**Comment by Ab2774** [comment]
Hi
are sure its 720p, not 1366 x 768?
also, make sure to use my EFI and follow the guide carefully, if you used `SSDT-PrtSc-F13`, `SSDT-Swap-Cmd-Alt` and `SSDT-KBD` all together you may have some issues, that's why I recommend using `SSDT-PS2K` for swapping Cmd-and-Alt and remapping F13 with `SSDT-KBD0`.
hope it's fixed now, if still not, upload your EFI please.
Cheers.

**Comment by Luka020** [comment]
Hi Ab2774,

Thanks for the fast responds :)
The screen is 1366 x 768. i used your latest EFI folder and changed a few things.

i added:
uia_exclude=HS07 to boot arguments
changed the graphics driver name to just "Intel HD Graphics 620"
Fast Boot.

Brightness does work manually through the settings menu and with FN+C/FN+P
If i go to settings and keyboard shortcuts these keys FN+C and FN+P are recognized as F14 and F15

I had the same issue in your first EFI, but i added a DSDT.aml from Olarila and than it worked. but in the new EFI 1.1.0 this method wil also work and ill get the button support but than the trackpad stops working. 

As a side note if i use the dsdt.aml in the latest 1.1.0 release i get some details under systeminformation.

ill send my EFI + the workaround dsdt.aml i used.
[EFI.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4474908/EFI.zip)
[DSDT.aml.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4474921/DSDT.aml.zip)

Hope this helps.

**Comment by Ab2774** [comment]
Hi 
I don't always recommend DSDTs for laptops because they're meant for PCs motherboard's, SSDTs are more controllable.
 if you don't want a patch you can just simply remove it unlike DSDTs as they're in the same file (.aml) and has a lack of changeability. 
anyways, I've done some changing to your `SSDT-PS2K` and `SSDT-KBD`(renamed as `SSDT-PS2K 2`) according to your DSDT.aml to match it.
if still doesn't work I have another solution to try
Cheers.
[EFI Test.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4475328/EFI.Test.zip)

**Comment by Luka020** [comment]
Hi Ab2774,

I really appreciate the help!
And thank you for the information.

Here is what i did:

- First i copied the whole new EFI in to the EFI drive - problem still presists.
- Then i deleted "SSDT-PS2K"  and renamed "SSDT-PS2K 2" to "SSDT-PS2K"- The problem still presists.

I hope it's still fixable :)

Cheers!

**Comment by Luka020** [comment]
Hi Ab2774,

I did some digging and used config.plist and ssdt's from moh_ameen,
so i deleted the my old config.plist and all the other ssdt's and used the ssdt's and config.plist from moh_ameen.

**Result** 
The keys are working and under keyboard shortcuts there is a new option "Display"
also the graphics card memory shrunk and is now 1536 instead of the 3000 something.

**EDIT**
I have discoverd that the config.plist platform-id is wrong it's showing Skylake CPU and we have a Kaby Lake i think the correct platform-id should be 0x59160000 under the section graphics with clover configurator.

i'll send you my EFI i hope you can fix the issue, because i like your work!
[EFI moh_ameen ssdt.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4476882/EFI.moh_ameen.ssdt.zip)

**Comment by Ab2774** [comment]
Hi 
I think the issue is originally from your backlight display, you're using a different model than this one, the 1080p backlight panel screens have working brightness with `SSDT-PNLF` unlike 768p screen that uses CFL backlight panel, thusly, getting it working requires `SSDT-PNLF-CFL`, that's why it was working with Clover `AddPNLF` fix because Clover generated automatically according to your hardware.
Anyways I've created two EFIs you can test it, one that patch `PNLF` manually and other that patch it automatically(`AddPNLF` Clover fix)
Hope I helped 
Cheers.
[EFI Test.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4477249/EFI.Test.zip)
[EFI Test #2.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4477252/EFI.Test.2.zip)

**Comment by Luka020** [comment]
Hi Ab2774,

I tried both but no luck :( Thank you for your time! i appriciate it.
- first EFI test nothing happend.
- second i had no trackpad support and also no backlight support

The new EFI with moh_ameen files uploaded here i used the files conifg.plist and the patches. 
now it works! 

Your theory about the AddPNLF could be right because when i unchecked it on the moh_ameen config.plist then my screen was not recognized and i could not use any backlight functions not even manuelly.


With your EFI i can use backlight but with FN+C/FN+P so thats a work around.
Still i find it interesting what could be the excat problem.

**Comment by Luka020** [comment]
Hi Ab2774,

I solved the issue!

What i did first i downloaded the latest **Clean EFI 1.1.0** than i took 2 lines of moh_ameen config.plist ACPI section. And added to the 1.1.0 config.plist

These are the lines:
- Change Method(_Q11,0,N) to XQ                 115F513131        00.58513131 00
- Change Method(_Q12,0,N) to XQ12             5F513132 00    58513132 00

i also added.  **SSDT-I320.aml** from moh_ameen "hotfixes"

and now i am all set :)) Marked as solved took me 1.5 day to figure this out!

Thank you for your time Ab2774 i really really appricitate it!
Also credits to moh_ameen for his amazing fixes! 

**MARKED AS SOLVED**

**Comment by Ab2774** [comment]
Hi Luka020.
In your DSDT the `PNLF` device is `PNLF-CFL` so that's what causes it not to work because of different types of screens, anyways, I'm really glad that it worked.
I don't recommend using Moh_Ameen EFI because it's uncompleted and missing lots of things.
anyways, that's some EFIs I've created from me EFI and only changed the `PNLF` device. 
Hope it will work 
Thanks
[EFI Test #2.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4477896/EFI.Test.2.zip)
[EFI Test #3.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4477897/EFI.Test.3.zip)
[EFI Test.zip](https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh/files/4477898/EFI.Test.zip)
